version: '3.8'

services:
  ecr-viewer:
    image: ghcr.io/cdcgov/phdi/ecr-viewer:v1.7.2
    restart: unless-stopped
    env_file: "ecr-viewer.env"
    ports:
      - "3000:3000"
    networks:
      - dibbs

  ingestion:
    image: ghcr.io/cdcgov/phdi/ingestion:v1.7.2
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - dibbs

  validation:
    image: ghcr.io/cdcgov/phdi/validation:v1.7.2
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - dibbs

  fhir-converter:
    image: ghcr.io/cdcgov/phdi/fhir-converter:v1.7.2
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - dibbs

  message-parser:
    image: ghcr.io/cdcgov/phdi/message-parser:v1.7.2
    restart: unless-stopped
    ports:
      - "8083:8080"
    networks:
      - dibbs

  trigger-code-reference:
    image: ghcr.io/cdcgov/phdi/trigger-code-reference:v1.7.2
    restart: unless-stopped
    ports:
      - "8084:8080"
    networks:
      - dibbs

  orchestration:
    image: ghcr.io/cdcgov/phdi/orchestration:v1.7.2
    env_file: "orchestration.env"
    restart: unless-stopped    
    ports:
      - "8085:8080"
    networks:
      - dibbs

  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - dibbs

volumes:
  portainer_data:

networks:
  dibbs: