version: 2
updates:
  - package-ecosystem: "docker"
    directories: 
      - "docker/ecr-viewer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
