version: '3.8'

services:
  ecr-viewer:
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/ecr-viewer:v2.0.0-beta
    restart: always
    env_file: "ecr-viewer.env"
    ports:
      - "3000:3000"
    networks:
      - dibbs

  ingestion:
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/ingestion:v2.0.0-beta
    restart: always
    ports:
      - "8080:8080"
    networks:
      - dibbs

  validation:
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/validation:v2.0.0-beta
    restart: always
    ports:
      - "8081:8080"
    networks:
      - dibbs

  fhir-converter:
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/fhir-converter:v2.0.0-beta
    restart: always
    ports:
      - "8082:8080"
    networks:
      - dibbs

  message-parser:
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/message-parser:v2.0.0-beta
    restart: always
    ports:
      - "8083:8080"
    networks:
      - dibbs

  trigger-code-reference:
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/trigger-code-reference:v2.0.0-beta
    restart: always
    ports:
      - "8084:8080"
    networks:
      - dibbs

  orchestration:
    image: ghcr.io/cdcgov/dibbs-ecr-viewer/orchestration:v2.0.0-beta
    env_file: "orchestration.env"
    restart: always    
    ports:
      - "8085:8080"
    networks:
      - dibbs

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - dibbs

volumes:
  portainer_data:

networks:
  dibbs: