site_name: DIBBs-In-A-Box
dev_addr: '0.0.0.0:80'

# Copyright
copyright: "© Centers for Disease Control and Prevention, 2025 | Confidential <!--BuildVersionNumber-->"

# Themes and Customization
theme: 
  name: readthedocs
  collapse_navigation: false
  prev_next_buttons_location: both
  sticky_navigation: true

extra_css:
  - hide.css