services:
  # PostgreSQL DB for custom query and value set storage
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=tefca_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 20

  # Next.js app with Flyway
  query-connector:
    image: ghcr.io/cdcgov/dibbs-query-connector/query-connector:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DATABASE_URL=postgres://postgres:pw@db:5432/tefca_db
      # Note: you must have a local .env file with the ERSD_API_KEY set to a key
      # obtained from the ERSD API at https://ersd.aimsplatform.org/#/api-keys
    depends_on:
      db:
        condition: service_healthy


  #Portainer
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: