services:
  # PostgreSQL DB for custom query and value set storage
  db:
    image: "postgres:17.4"
    restart: always
    ports:
      - "5432:5432"
    env_file: "db.env"
    volumes:
      - ./vs_dump.sql:/docker-entrypoint-initdb.d/vs_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 20

# Flyway migrations and DB version control
  flyway:
    image: flyway/flyway:11-alpine
    command: -configFiles=/flyway/conf/flyway.conf -schemas=public -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_started

  # Next.js app
  query-connector:
    image: ghcr.io/cdcgov/dibbs-query-connector/query-connector:latest
    restart: always
    tty: true
    ports:
      - "3000:3000"
    env_file: "dibbs-query-connector.env"

      # Note: you must have a local .env file with the ERSD_API_KEY set to a key
      # obtained from the ERSD API at https://ersd.aimsplatform.org/#/api-keys
    depends_on:
      db:
        condition: service_healthy


  #Portainer
  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  docs:
    build:
      context: ./../docs
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  portainer_data: