services:
  # PostgreSQL DB for custom query and value set storage
  db:
    image: "postgres:17.4"
    restart: always
    ports:
      - "5432:5432"
    env_file: "db.env"
    volumes:
      - ./vs_dump.sql:/docker-entrypoint-initdb.d/vs_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 20

# Flyway migrations and DB version control
  flyway:
    image: flyway/flyway:11-alpine
    command: -configFiles=/flyway/conf/flyway.conf -schemas=public -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_started

  # Next.js app
  query-connector:
    image: ghcr.io/cdcgov/$DIBBS_SERVICE/query-connector:$DIBBS_VERSION
    restart: always
    tty: true
    ports:
      - "3000:3000"
    env_file: "dibbs-query-connector.env"

      # Note: you must have a local .env file with the ERSD_API_KEY set to a key
      # obtained from the ERSD API at https://ersd.aimsplatform.org/#/api-keys
    depends_on:
      db:
        condition: service_healthy


  #Portainer
  # portainer:
  #   image: portainer/portainer-ce
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  docs:
    build:
      context: ./../docs
      dockerfile: Dockerfile
    ports:
      - "80:80"


  # Aidbox
  aidbox_db:
    image: healthsamurai/aidboxdb:17
    volumes:
      - aidbox_pg_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_USER: aidbox
      POSTGRES_PORT: "5432"
      POSTGRES_DB: aidbox
      POSTGRES_PASSWORD: gOxAmiyiz4

  aidbox:
    image: healthsamurai/aidboxone:stable
    pull_policy: always
    depends_on:
      - aidbox_db
    ports:
      - 8080:8080
    environment:
      AIDBOX_TERMINOLOGY_SERVICE_BASE_URL: https://tx.fhir.org/r4
      AIDBOX_FHIR_PACKAGES: hl7.fhir.r4.core#4.0.1
      AIDBOX_FHIR_SCHEMA_VALIDATION: true
      AIDBOX_CREATED_AT_URL: https://aidbox.app/ex/createdAt
      AIDBOX_CLIENT_SECRET: L6AGe_5V2O
      AIDBOX_CORRECT_AIDBOX_FORMAT: true
      AIDBOX_ADMIN_PASSWORD: OC1MzJ5QNV
      AIDBOX_COMPLIANCE: enabled
      AIDBOX_SECURITY_AUDIT__LOG_ENABLED: true
      BOX_SEARCH_FHIR__COMPARISONS: true
      PGHOST: aidbox_db
      BOX_COMPATIBILITY_VALIDATION_JSON__SCHEMA_REGEX: "#{:fhir-datetime}"
      BOX_SEARCH_AUTHORIZE_INLINE_REQUESTS: true
      PGUSER: aidbox
      AIDBOX_PORT: 8080
      PGDATABASE: aidbox
      PGPASSWORD: gOxAmiyiz4
      PGPORT: "5432"
      BOX_SEARCH_INCLUDE_CONFORMANT: true

  aidbox-seeder:
    build:
      context: .
      dockerfile: Dockerfile.aidbox-seeder
    volumes:
      - ./src/app/tests/assets/GoldenSickPatient.json:/data/GoldenSickPatient.json
    environment:
      - AIDBOX_BASE_URL=http://aidbox:8080
      - APP_HOSTNAME=http://host.docker.internal:3000
    depends_on:
      db:
        condition: service_healthy
      aidbox:
        condition: service_started
      flyway:
        condition: service_completed_successfully

volumes:
  aidbox_pg_data:
      